"""Add portfolio model and field

Revision ID: 68befaa9e341
Revises: cd0967fae312
Create Date: 2024-10-17 04:16:21.646356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68befaa9e341'
down_revision = 'cd0967fae312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'portfolio', ['portfolio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('portfolio_id')

    op.drop_table('portfolio')
    # ### end Alembic commands ###
